spring:
  datasource:
    toysdb:
      password: ${MYSQL_PASSWORD:Asd.123*-}
      username: ${MYSQL_USER:root}
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/mycloths?useSSL=false&allowMultiQueries=true&serverTimezone=UTC}
      ddl-auto: update
      hikari:
        idleTimeout: 600000
        maximumPoolSize: 2
        connectionTimeout: 30000
        maxLifetime: 1800000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect